defaults: &defaults
  name:
    length:
      minimum:  3
      maximum:  100

  description:
    length:
      minimum: 10
      maximum: 100

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults