defaults: &defaults
  pagination:
    per: 16

  name:
    length:
      minimum:  3
      maximum:  60

  description:
    length:
      minimum: 10
      maximum: 100

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults